development:
   adapter: mysql
   database: twitter
   username: root
   password: 123
   host: localhost
  
test:
   adapter: mysql
   database: twitter
   username: root
   password: 123
   host: localhost
   
production:
   adapter: mysql
   database: twitter
   username: root
   password: 123
   host: localhost